---
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev:  ""
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=.

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
    - id: helmlint
    - id: shellcheck