# Default values for hiro-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Custom prometheus values
prometheus:
  # Accessed by InfluxDB.

  server:
    remoteWrite:
      - url: "http://hiro-telemetry-influxdb.monitoring:8086/api/v1/prom/write?db=prometheus&u=admin&p=admin"

    global:
      ## How frequently to scrape targets by default
      ##
      scrape_interval: 1m
      ## How long until a scrape request times out
      ##
      scrape_timeout: 11s
      ## How frequently to evaluate rules
      ##
      evaluation_interval: 1m
  kube-state-metrics:
    ## If false, kube-state-metrics sub-chart will not be installed
    ##
    enabled: true

  alertmanager:
    ## If false, alertmanager will not be installed
    enabled: true

grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus-hiro
        type: prometheus
        # this is clusterIP address of telemetry-prometheus-server
        url: http://hiro-telemetry-prometheus-server:80
        access: proxy
        isDefault: true


influxdb:
  image:
    repository: "influxdb"
    tag: "1.8" # InfluxDB 2.0 is not directly supported with prometheus
    pullPolicy: IfNotPresent

  env:
    - name: INFLUXDB_DB
      value: "prometheus"
    - name: INFLUXDB_ADMIN_USER
      value: "admin"
    - name: INFLUXDB_ADMIN_PASSWORD
      value: "admin"

