apiVersion: v2
name: monitoring-stack
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.9"


dependencies:
  - name: prometheus
    version: 25.10.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 7.3.9
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: influxdb2
    version: 2.1.2
    repository: https://helm.influxdata.com/
    condition: influxdb.enabled
  - name: telegraf
    version: 1.8.45
    repository: https://helm.influxdata.com/
    condition: telegraf.enabled
  - name: fluentd-sidecar-injector
    version: 0.4.3
    repository: https://h3poteto.github.io/charts/stable
    condition: fluentd-sidecar-injector.enabled
  - name: loki-stack
    version: 2.10.1
    repository: https://grafana.github.io/helm-charts
    condition: loki-stack.enabled
  - name: kubernetes-event-exporter
    version: 3.0.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kubernetes-event-exporter.enabled
  - name: prometheus-snmp-exporter
    version: 5.1.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-snmp-exporter.enabled
  - name: kepler
    version: 0.5.5
    repository: https://sustainable-computing-io.github.io/kepler-helm-chart
    condition: kepler.enabled
  - name: dcgm-exporter
    version: 2.4.0
    repository: https://nvidia.github.io/gpu-monitoring-tools/helm-charts
    condition: dcgm-exporter.enabled
  - name: idrac-exporter
    version: 0.1.0
    repository: https://hiro-microdatacenters-bv.github.io/idrac-exporter/helm-charts
    condition: idrac-exporter.enabled
  - name: k8s-ephemeral-storage-metrics
    version: 1.11.1
    repository: https://jmcgrath207.github.io/k8s-ephemeral-storage-metrics/chart
    condition: k8s-ephemeral-storage-metrics.enabled