{
 "title": "Basic Monitoring",
 "tags": [ "linux" ],
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  { "title": "Simplified Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes" }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Usage By Cores",
   "type": "graph",
   "description": "Percentage of each CPU core being used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage By Process",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total[5m])) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[2m])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[2m])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": " node_memory_Cached_bytes",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes- node_memory_SwapFree_bytes)",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    { "legendFormat": "{{device}} - Reads completed" },
    {
     "expr": "irate(node_disk_writes_completed_total[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs'} - node_filesystem_avail_bytes{device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  }
 ]
}