name: Build Helm Chart

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Publish Release Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ github.token }}
        charts_dir: "./"
        target_dir: "./helm-charts"
